#Ruthann Biel,  Lab10

lab10: lab10.o ParseCmd.o ProcessExtCmd.o RunExtCmd.o Redirection.o  
	gcc lab10.o ParseCmd.o ProcessExtCmd.o Redirection.o RunExtCmd.o -o lab10

lab10.o: lab10.c lab9_10.h 
	gcc -c lab10.c -Wall

ParseCmd.o: ParseCmd.c lab9_10.h 
	gcc -c ParseCmd.c -Wall

ProcessExtCmd.o: ProcessExtCmd.c lab9_10.h 
	gcc -c ProcessExtCmd.c -Wall

Redirection.o: Redirection.c lab9_10.h 
	gcc -c Redirection.c -Wall

RunExtCmd.o: RunExtCmd.c lab9_10.h 
	gcc -c RunExtCmd.c -Wall
