---
title: "lab4-2"
author: "Austin Melendez"
date: "2026-02-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Section 4.8: Exercises 14, 16

## Exercise 14
### A
```{r}
library(ISLR2)
data(Auto)

# Create binary mpg
mpg01 <- ifelse(Auto$mpg > median(Auto$mpg), 1, 0)

Auto2 <- data.frame(mpg01, Auto)
```

### B
```{r}
summary(Auto2)

plot(Auto2)
```

### C
Train/test split

```{r}
set.seed(1)
train_idx <- sample(1:nrow(Auto2), nrow(Auto2)/2)

train <- Auto2[train_idx, ]
test  <- Auto2[-train_idx, ]

train_X <- train[, c("displacement", "horsepower", "weight")]
test_X  <- test[,  c("displacement", "horsepower", "weight")]
train_y <- train$mpg01
test_y  <- test$mpg01
```

### D
LDA

```{r}
library(MASS)

lda_fit <- lda(mpg01 ~ displacement + horsepower + weight, data = train)
lda_pred <- predict(lda_fit, test)$class

# Calculate test error
mean(lda_pred != test_y)
```

### E
QDA

```{r}
qda_fit <- qda(mpg01 ~ displacement + horsepower + weight, data = train)
qda_pred <- predict(qda_fit, test)$class

# Test erorr
mean(qda_pred != test_y)
```

### F
Logistic Regression

```{r}
log_fit <- glm(mpg01 ~ displacement + horsepower + weight,
                 data = train, family = binomial)

log_probs <- predict(log_fit, test, type = "response")
log_pred <- ifelse(log_probs > 0.5, 1, 0)

mean(log_pred != test_y)
```

### G
Naive Bayes

```{r}
library(e1071)

nb_fit <- naiveBayes(as.factor(mpg01) ~ displacement + horsepower + weight,
                     data = train)

nb_pred <- predict(nb_fit, test)

mean(nb_pred != test_y)
```

### H
KNN with various K values

```{r}
library(class)

train_std <- scale(train_X)
test_std  <- scale(test_X, center = attr(train_std, "scaled:center"),
                            scale  = attr(train_std, "scaled:scale"))

Ks <- c(1, 3, 5, 7, 10, 15)
errors <- rep(0, length(Ks))

for (i in 1:length(Ks)) {
  pred_knn <- knn(train_std, test_std, train_y, k = Ks[i])
  errors[i] <- mean(pred_knn != test_y)
}

data.frame(K = Ks, Test_Error = errors)
```

## Exercise 16

```{r}
# Create binary response
data(Boston)
med.crim <- median(Boston$crim)
CrimeHigh <- ifelse(Boston$crim > med.crim, 1, 0)
Boston$CrimeHigh <- as.factor(CrimeHigh)

# Train/Test split
set.seed(1)
train.idx <- sample(1:nrow(Boston), nrow(Boston)/2)
train <- Boston[train.idx, ]
test  <- Boston[-train.idx, ]

train.Y <- train$CrimeHigh
test.Y  <- test$CrimeHigh

vars <- c("lstat", "rm", "tax", "indus")

# Logistic Regression
log.fit <- glm(CrimeHigh ~ . -crim, data=train, family=binomial)
log.prob <- predict(log.fit, newdata=test, type="response")
log.pred <- ifelse(log.prob > 0.5, 1, 0)
log.acc <- mean(log.pred == test.Y)

# LDA
lda.fit <- lda(CrimeHigh ~ . -crim, data=train)
lda.pred <- predict(lda.fit, newdata=test)$class
lda.acc <- mean(lda.pred == test.Y)

# Naive Bayes
nb.fit <- naiveBayes(CrimeHigh ~ . -crim, data=train)
nb.pred <- predict(nb.fit, newdata=test)
nb.acc <- mean(nb.pred == test.Y)

# KNN
train.X <- train[, vars]
test.X  <- test[, vars]

set.seed(1)
knn.pred <- knn(train.X, test.X, train.Y, k = 5)
knn.acc <- mean(knn.pred == test.Y)


#Print results
results <- data.frame(
  Method = c("Logistic Regression", "LDA", "Naive Bayes", "KNN = 5"),
  Accuracy = c(log.acc, lda.acc, nb.acc, knn.acc)
)

print(results)
```
Based on our findings, the model with the most accuracy is the `Logistic Regression model`, followed closely by the `KNN model with k = 5`.

